/**
 *
 *  Transactions.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Transactions.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::transaction;

const std::string Transactions::Cols::_id = "\"id\"";
const std::string Transactions::Cols::_user_id = "\"user_id\"";
const std::string Transactions::Cols::_market_id = "\"market_id\"";
const std::string Transactions::Cols::_option_id = "\"option_id\"";
const std::string Transactions::Cols::_transaction_type = "\"transaction_type\"";
const std::string Transactions::Cols::_number_of_shares = "\"number_of_shares\"";
const std::string Transactions::Cols::_price_per_share = "\"price_per_share\"";
const std::string Transactions::Cols::_created_at = "\"created_at\"";
const std::string Transactions::primaryKeyName = "id";
const bool Transactions::hasPrimaryKey = true;
const std::string Transactions::tableName = "\"transactions\"";

const std::vector<typename Transactions::MetaData> Transactions::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"user_id","std::string","uuid",0,0,0,1},
{"market_id","std::string","uuid",0,0,0,1},
{"option_id","std::string","uuid",0,0,0,1},
{"transaction_type","std::string","character varying",50,0,0,1},
{"number_of_shares","std::string","numeric",0,0,0,1},
{"price_per_share","std::string","numeric",0,0,0,1},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &Transactions::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Transactions::Transactions(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["market_id"].isNull())
        {
            marketId_=std::make_shared<std::string>(r["market_id"].as<std::string>());
        }
        if(!r["option_id"].isNull())
        {
            optionId_=std::make_shared<std::string>(r["option_id"].as<std::string>());
        }
        if(!r["transaction_type"].isNull())
        {
            transactionType_=std::make_shared<std::string>(r["transaction_type"].as<std::string>());
        }
        if(!r["number_of_shares"].isNull())
        {
            numberOfShares_=std::make_shared<std::string>(r["number_of_shares"].as<std::string>());
        }
        if(!r["price_per_share"].isNull())
        {
            pricePerShare_=std::make_shared<std::string>(r["price_per_share"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            marketId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            optionId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            transactionType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            numberOfShares_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            pricePerShare_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Transactions::Transactions(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            marketId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            optionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            transactionType_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            numberOfShares_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            pricePerShare_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Transactions::Transactions(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("market_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["market_id"].isNull())
        {
            marketId_=std::make_shared<std::string>(pJson["market_id"].asString());
        }
    }
    if(pJson.isMember("option_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["option_id"].isNull())
        {
            optionId_=std::make_shared<std::string>(pJson["option_id"].asString());
        }
    }
    if(pJson.isMember("transaction_type"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["transaction_type"].isNull())
        {
            transactionType_=std::make_shared<std::string>(pJson["transaction_type"].asString());
        }
    }
    if(pJson.isMember("number_of_shares"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["number_of_shares"].isNull())
        {
            numberOfShares_=std::make_shared<std::string>(pJson["number_of_shares"].asString());
        }
    }
    if(pJson.isMember("price_per_share"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["price_per_share"].isNull())
        {
            pricePerShare_=std::make_shared<std::string>(pJson["price_per_share"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Transactions::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            marketId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            optionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            transactionType_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            numberOfShares_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            pricePerShare_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Transactions::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("market_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["market_id"].isNull())
        {
            marketId_=std::make_shared<std::string>(pJson["market_id"].asString());
        }
    }
    if(pJson.isMember("option_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["option_id"].isNull())
        {
            optionId_=std::make_shared<std::string>(pJson["option_id"].asString());
        }
    }
    if(pJson.isMember("transaction_type"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["transaction_type"].isNull())
        {
            transactionType_=std::make_shared<std::string>(pJson["transaction_type"].asString());
        }
    }
    if(pJson.isMember("number_of_shares"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["number_of_shares"].isNull())
        {
            numberOfShares_=std::make_shared<std::string>(pJson["number_of_shares"].asString());
        }
    }
    if(pJson.isMember("price_per_share"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["price_per_share"].isNull())
        {
            pricePerShare_=std::make_shared<std::string>(pJson["price_per_share"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &Transactions::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getId() const noexcept
{
    return id_;
}
void Transactions::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void Transactions::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename Transactions::PrimaryKeyType & Transactions::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Transactions::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getUserId() const noexcept
{
    return userId_;
}
void Transactions::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[1] = true;
}
void Transactions::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[1] = true;
}

const std::string &Transactions::getValueOfMarketId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(marketId_)
        return *marketId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getMarketId() const noexcept
{
    return marketId_;
}
void Transactions::setMarketId(const std::string &pMarketId) noexcept
{
    marketId_ = std::make_shared<std::string>(pMarketId);
    dirtyFlag_[2] = true;
}
void Transactions::setMarketId(std::string &&pMarketId) noexcept
{
    marketId_ = std::make_shared<std::string>(std::move(pMarketId));
    dirtyFlag_[2] = true;
}

const std::string &Transactions::getValueOfOptionId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(optionId_)
        return *optionId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getOptionId() const noexcept
{
    return optionId_;
}
void Transactions::setOptionId(const std::string &pOptionId) noexcept
{
    optionId_ = std::make_shared<std::string>(pOptionId);
    dirtyFlag_[3] = true;
}
void Transactions::setOptionId(std::string &&pOptionId) noexcept
{
    optionId_ = std::make_shared<std::string>(std::move(pOptionId));
    dirtyFlag_[3] = true;
}

const std::string &Transactions::getValueOfTransactionType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(transactionType_)
        return *transactionType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getTransactionType() const noexcept
{
    return transactionType_;
}
void Transactions::setTransactionType(const std::string &pTransactionType) noexcept
{
    transactionType_ = std::make_shared<std::string>(pTransactionType);
    dirtyFlag_[4] = true;
}
void Transactions::setTransactionType(std::string &&pTransactionType) noexcept
{
    transactionType_ = std::make_shared<std::string>(std::move(pTransactionType));
    dirtyFlag_[4] = true;
}

const std::string &Transactions::getValueOfNumberOfShares() const noexcept
{
    static const std::string defaultValue = std::string();
    if(numberOfShares_)
        return *numberOfShares_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getNumberOfShares() const noexcept
{
    return numberOfShares_;
}
void Transactions::setNumberOfShares(const std::string &pNumberOfShares) noexcept
{
    numberOfShares_ = std::make_shared<std::string>(pNumberOfShares);
    dirtyFlag_[5] = true;
}
void Transactions::setNumberOfShares(std::string &&pNumberOfShares) noexcept
{
    numberOfShares_ = std::make_shared<std::string>(std::move(pNumberOfShares));
    dirtyFlag_[5] = true;
}

const std::string &Transactions::getValueOfPricePerShare() const noexcept
{
    static const std::string defaultValue = std::string();
    if(pricePerShare_)
        return *pricePerShare_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Transactions::getPricePerShare() const noexcept
{
    return pricePerShare_;
}
void Transactions::setPricePerShare(const std::string &pPricePerShare) noexcept
{
    pricePerShare_ = std::make_shared<std::string>(pPricePerShare);
    dirtyFlag_[6] = true;
}
void Transactions::setPricePerShare(std::string &&pPricePerShare) noexcept
{
    pricePerShare_ = std::make_shared<std::string>(std::move(pPricePerShare));
    dirtyFlag_[6] = true;
}

const ::trantor::Date &Transactions::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Transactions::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Transactions::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}

void Transactions::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Transactions::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "user_id",
        "market_id",
        "option_id",
        "transaction_type",
        "number_of_shares",
        "price_per_share",
        "created_at"
    };
    return inCols;
}

void Transactions::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMarketId())
        {
            binder << getValueOfMarketId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOptionId())
        {
            binder << getValueOfOptionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTransactionType())
        {
            binder << getValueOfTransactionType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getNumberOfShares())
        {
            binder << getValueOfNumberOfShares();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPricePerShare())
        {
            binder << getValueOfPricePerShare();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Transactions::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void Transactions::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMarketId())
        {
            binder << getValueOfMarketId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOptionId())
        {
            binder << getValueOfOptionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTransactionType())
        {
            binder << getValueOfTransactionType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getNumberOfShares())
        {
            binder << getValueOfNumberOfShares();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPricePerShare())
        {
            binder << getValueOfPricePerShare();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Transactions::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getMarketId())
    {
        ret["market_id"]=getValueOfMarketId();
    }
    else
    {
        ret["market_id"]=Json::Value();
    }
    if(getOptionId())
    {
        ret["option_id"]=getValueOfOptionId();
    }
    else
    {
        ret["option_id"]=Json::Value();
    }
    if(getTransactionType())
    {
        ret["transaction_type"]=getValueOfTransactionType();
    }
    else
    {
        ret["transaction_type"]=Json::Value();
    }
    if(getNumberOfShares())
    {
        ret["number_of_shares"]=getValueOfNumberOfShares();
    }
    else
    {
        ret["number_of_shares"]=Json::Value();
    }
    if(getPricePerShare())
    {
        ret["price_per_share"]=getValueOfPricePerShare();
    }
    else
    {
        ret["price_per_share"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

Json::Value Transactions::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMarketId())
            {
                ret[pMasqueradingVector[2]]=getValueOfMarketId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getOptionId())
            {
                ret[pMasqueradingVector[3]]=getValueOfOptionId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTransactionType())
            {
                ret[pMasqueradingVector[4]]=getValueOfTransactionType();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getNumberOfShares())
            {
                ret[pMasqueradingVector[5]]=getValueOfNumberOfShares();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPricePerShare())
            {
                ret[pMasqueradingVector[6]]=getValueOfPricePerShare();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[7]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getMarketId())
    {
        ret["market_id"]=getValueOfMarketId();
    }
    else
    {
        ret["market_id"]=Json::Value();
    }
    if(getOptionId())
    {
        ret["option_id"]=getValueOfOptionId();
    }
    else
    {
        ret["option_id"]=Json::Value();
    }
    if(getTransactionType())
    {
        ret["transaction_type"]=getValueOfTransactionType();
    }
    else
    {
        ret["transaction_type"]=Json::Value();
    }
    if(getNumberOfShares())
    {
        ret["number_of_shares"]=getValueOfNumberOfShares();
    }
    else
    {
        ret["number_of_shares"]=Json::Value();
    }
    if(getPricePerShare())
    {
        ret["price_per_share"]=getValueOfPricePerShare();
    }
    else
    {
        ret["price_per_share"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool Transactions::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("market_id"))
    {
        if(!validJsonOfField(2, "market_id", pJson["market_id"], err, true))
            return false;
    }
    else
    {
        err="The market_id column cannot be null";
        return false;
    }
    if(pJson.isMember("option_id"))
    {
        if(!validJsonOfField(3, "option_id", pJson["option_id"], err, true))
            return false;
    }
    else
    {
        err="The option_id column cannot be null";
        return false;
    }
    if(pJson.isMember("transaction_type"))
    {
        if(!validJsonOfField(4, "transaction_type", pJson["transaction_type"], err, true))
            return false;
    }
    else
    {
        err="The transaction_type column cannot be null";
        return false;
    }
    if(pJson.isMember("number_of_shares"))
    {
        if(!validJsonOfField(5, "number_of_shares", pJson["number_of_shares"], err, true))
            return false;
    }
    else
    {
        err="The number_of_shares column cannot be null";
        return false;
    }
    if(pJson.isMember("price_per_share"))
    {
        if(!validJsonOfField(6, "price_per_share", pJson["price_per_share"], err, true))
            return false;
    }
    else
    {
        err="The price_per_share column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Transactions::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Transactions::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("market_id"))
    {
        if(!validJsonOfField(2, "market_id", pJson["market_id"], err, false))
            return false;
    }
    if(pJson.isMember("option_id"))
    {
        if(!validJsonOfField(3, "option_id", pJson["option_id"], err, false))
            return false;
    }
    if(pJson.isMember("transaction_type"))
    {
        if(!validJsonOfField(4, "transaction_type", pJson["transaction_type"], err, false))
            return false;
    }
    if(pJson.isMember("number_of_shares"))
    {
        if(!validJsonOfField(5, "number_of_shares", pJson["number_of_shares"], err, false))
            return false;
    }
    if(pJson.isMember("price_per_share"))
    {
        if(!validJsonOfField(6, "price_per_share", pJson["price_per_share"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Transactions::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Transactions::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
